### PR TITLE
Structural adjustments

### PR DESCRIPTION
**Pull request by moimikey**
Here's your first PR :+1:. let me know if you'd like anything adjusted.

### CODE REVIEW

**Comment by moimikey** [comment]
aww. second rather.

**Comment by kohei-takata** [comment]
Thanks!LGTM
Would you add your favorite repository(s) to `repository.json`?
So that the repository will get stars, if you want.

**Comment by moimikey** [comment]
totally!

**Comment by kohei-takata** [comment]
Thanks!

**Pull request merged**
